// Quellenverzeichnis für "Die Geschichte des Bewegtbildes"
// Alle Quellen wurden im Rahmen des Faktenchecks (März 2026) geprüft.

export interface Source {
  id: string;
  title: string;
  author?: string;
  publisher: string;
  url?: string;
  type: "wikipedia" | "buch" | "artikel" | "archiv" | "offiziell" | "akademisch";
  epochen: string[]; // Welche Epochen / Themen diese Quelle abdeckt
}

export const sources: Source[] = [
  // ── VORFILM ────────────────────────────────────────────────────────────────────
  {
    id: "wiki-camera-obscura",
    title: "Camera obscura",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/Camera_obscura",
    type: "wikipedia",
    epochen: ["Vorfilm"],
  },
  {
    id: "ibn-alhaytham",
    title: "Ibn al-Haytham: Father of Modern Optics",
    publisher: "PMC / National Library of Medicine",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6074172/",
    type: "akademisch",
    epochen: ["Vorfilm"],
  },
  {
    id: "wiki-magic-lantern",
    title: "Magic lantern",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/Magic_lantern",
    type: "wikipedia",
    epochen: ["Vorfilm"],
  },
  {
    id: "histinfo-phenakistiskop",
    title: "The Phenakistoscope, the First Device to Demonstrate the Illusion of Motion",
    publisher: "historyofinformation.com",
    url: "https://www.historyofinformation.com/detail.php?id=3675",
    type: "artikel",
    epochen: ["Vorfilm"],
  },
  {
    id: "smarthistory-muybridge",
    title: "Eadweard Muybridge, The Horse in Motion",
    publisher: "Smarthistory",
    url: "https://smarthistory.org/eadweard-muybridge-the-horse-in-motion/",
    type: "akademisch",
    epochen: ["Vorfilm"],
  },
  {
    id: "wiki-kinetoscope",
    title: "Kinetoscope",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/Kinetoscope",
    type: "wikipedia",
    epochen: ["Vorfilm"],
  },
  {
    id: "wiki-zoopraxiscope",
    title: "Zoopraxiscope",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/Zoopraxiscope",
    type: "wikipedia",
    epochen: ["Vorfilm"],
  },
  // ── GEBURT DES KINOS ──────────────────────────────────────────────────────────
  {
    id: "wiki-salon-indien",
    title: "Salon Indien du Grand Café",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/Salon_Indien_du_Grand_Caf%C3%A9",
    type: "wikipedia",
    epochen: ["Geburt"],
  },
  {
    id: "sciencemuseum-lumiere",
    title: "The Lumière brothers: pioneers of cinema and photography",
    publisher: "Science and Media Museum (Bradford)",
    url: "https://blog.scienceandmediamuseum.org.uk/the-lumiere-brothers-pioneers-of-cinema-and-colour-photography/",
    type: "archiv",
    epochen: ["Geburt"],
  },
  {
    id: "cracked-melies",
    title: "How A Jammed Camera Helped Create All Of Science-Fiction",
    publisher: "Cracked.com",
    url: "https://www.cracked.com/article_31300_how-a_jammed_camera_helped_create_all_of_science-fiction.html",
    type: "artikel",
    epochen: ["Geburt"],
  },
  {
    id: "wiki-melies-filmography",
    title: "Georges Méliès filmography",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/Georges_M%C3%A9li%C3%A8s_filmography",
    type: "wikipedia",
    epochen: ["Geburt"],
  },
  {
    id: "wiki-trip-to-moon",
    title: "A Trip to the Moon",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/A_Trip_to_the_Moon",
    type: "wikipedia",
    epochen: ["Geburt"],
  },
  // ── FILMSPRACHE ───────────────────────────────────────────────────────────────
  {
    id: "wiki-birth-of-nation",
    title: "The Birth of a Nation",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/The_Birth_of_a_Nation",
    type: "wikipedia",
    epochen: ["Filmsprache"],
  },
  {
    id: "bbc-birth-of-nation",
    title: "The Birth of a Nation: The most racist movie ever made?",
    publisher: "BBC Culture",
    url: "https://www.bbc.com/culture/article/20150206-the-most-racist-movie-ever-made",
    type: "artikel",
    epochen: ["Filmsprache"],
  },
  {
    id: "wiki-kuleshov",
    title: "Kuleshov effect",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/Kuleshov_effect",
    type: "wikipedia",
    epochen: ["Filmsprache"],
  },
  {
    id: "britannica-potemkin",
    title: "Battleship Potemkin",
    publisher: "Encyclopædia Britannica",
    url: "https://www.britannica.com/topic/Battleship-Potemkin",
    type: "akademisch",
    epochen: ["Filmsprache"],
  },
  {
    id: "wiki-man-with-camera",
    title: "Man with a Movie Camera",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/Man_with_a_Movie_Camera",
    type: "wikipedia",
    epochen: ["Filmsprache"],
  },
  {
    id: "wiki-german-expressionism",
    title: "German expressionist cinema",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/German_expressionist_cinema",
    type: "wikipedia",
    epochen: ["Filmsprache"],
  },
  {
    id: "wiki-schufftan",
    title: "Schüfftan process",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/Sch%C3%BCfftan_process",
    type: "wikipedia",
    epochen: ["Filmsprache"],
  },
  // ── TONFILM ───────────────────────────────────────────────────────────────────
  {
    id: "wiki-jazz-singer",
    title: "The Jazz Singer (1927)",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/The_Jazz_Singer",
    type: "wikipedia",
    epochen: ["Tonfilm"],
  },
  {
    id: "guardian-jolson",
    title: "You ain't heard nothin' yet: the moment Al Jolson sounded the death knell for silent film",
    publisher: "The Guardian",
    url: "https://www.theguardian.com/film/2017/oct/07/how-al-jolson-jazz-singer-1927-changed-film-industry-foreever",
    type: "artikel",
    epochen: ["Tonfilm"],
  },
  {
    id: "britannica-blimp",
    title: "Blimp – soundproof camera housing",
    publisher: "Encyclopædia Britannica",
    url: "https://www.britannica.com/technology/blimp-soundproof-camera-housing",
    type: "akademisch",
    epochen: ["Tonfilm"],
  },
  {
    id: "eastman-technicolor",
    title: "Three-Strip Camera – Technicolor",
    publisher: "George Eastman Museum",
    url: "https://www.eastman.org/technicolor/technology/three-strip-camera",
    type: "archiv",
    epochen: ["Tonfilm"],
  },
  {
    id: "disney-flowers-trees",
    title: "Flowers and Trees at 90: Disney's First Color Movie",
    publisher: "Walt Disney Family Museum",
    url: "https://www.waltdisney.org/blog/flowers-and-trees-first-color-movie",
    type: "archiv",
    epochen: ["Tonfilm"],
  },
  {
    id: "wiki-becky-sharp",
    title: "Becky Sharp (1935 film)",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/Becky_Sharp_(film)",
    type: "wikipedia",
    epochen: ["Tonfilm"],
  },
  {
    id: "wiki-wizard-of-oz",
    title: "The Wizard of Oz (1939 film)",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/The_Wizard_of_Oz_(1939_film)",
    type: "wikipedia",
    epochen: ["Tonfilm"],
  },
  // ── GOLDENES HOLLYWOOD ────────────────────────────────────────────────────────
  {
    id: "wiki-orson-welles",
    title: "Orson Welles",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/Orson_Welles",
    type: "wikipedia",
    epochen: ["Goldenes Hollywood"],
  },
  {
    id: "wiki-gregg-toland",
    title: "Gregg Toland",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/Gregg_Toland",
    type: "wikipedia",
    epochen: ["Goldenes Hollywood"],
  },
  {
    id: "asc-citizen-kane",
    title: "Realism for Citizen Kane",
    publisher: "American Cinematographer (ASC)",
    url: "https://theasc.com/articles/realism-for-citizen-kane",
    type: "akademisch",
    epochen: ["Goldenes Hollywood"],
  },
  {
    id: "wiki-film-noir",
    title: "Film noir",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/Film_noir",
    type: "wikipedia",
    epochen: ["Goldenes Hollywood"],
  },
  {
    id: "wiki-cinemascope",
    title: "CinemaScope",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/CinemaScope",
    type: "wikipedia",
    epochen: ["Goldenes Hollywood"],
  },
  {
    id: "wiki-dolly-zoom",
    title: "Dolly zoom",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/Dolly_zoom",
    type: "wikipedia",
    epochen: ["Goldenes Hollywood"],
  },
  // ── NOUVELLE VAGUE ────────────────────────────────────────────────────────────
  {
    id: "redsharknews-arriflex",
    title: "The ARRI 35II: the camera that defined a generation of film directors",
    publisher: "RedShark News",
    url: "https://www.redsharknews.com/production/item/5208-the-arri-35ii-the-camera-that-defined-a-generation-of-film-directors",
    type: "artikel",
    epochen: ["Nouvelle Vague"],
  },
  {
    id: "wiki-breathless",
    title: "Breathless (1960 film) – À bout de souffle",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/Breathless_(1960_film)",
    type: "wikipedia",
    epochen: ["Nouvelle Vague"],
  },
  {
    id: "wiki-auteur-theory",
    title: "Auteur theory",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/Auteur_theory",
    type: "wikipedia",
    epochen: ["Nouvelle Vague"],
  },
  {
    id: "wiki-italian-neorealism",
    title: "Italian neorealism",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/Italian_neorealism",
    type: "wikipedia",
    epochen: ["Nouvelle Vague"],
  },
  // ── NEW HOLLYWOOD ─────────────────────────────────────────────────────────────
  {
    id: "wiki-steadicam",
    title: "Steadicam",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/Steadicam",
    type: "wikipedia",
    epochen: ["New Hollywood"],
  },
  {
    id: "asc-steadicam-shining",
    title: "The Steadicam and The Shining Revisited",
    publisher: "American Cinematographer (ASC)",
    url: "https://theasc.com/articles/steadicam-shining-revisited",
    type: "akademisch",
    epochen: ["New Hollywood"],
  },
  {
    id: "history-jaws-blockbuster",
    title: "How Jaws Gave Rise to the Summer Blockbuster",
    publisher: "History.com",
    url: "https://www.history.com/articles/jaws-movie-shark-blockbuster",
    type: "artikel",
    epochen: ["New Hollywood"],
  },
  {
    id: "ilm-about",
    title: "About ILM – Industrial Light & Magic",
    publisher: "ILM (offiziell)",
    url: "https://www.ilm.com/about/",
    type: "offiziell",
    epochen: ["New Hollywood", "CGI-Ära"],
  },
  {
    id: "variety-dolby-star-wars",
    title: "George Lucas and Dolby Sound: How Star Wars Changed Cinema Audio",
    publisher: "Variety",
    url: "https://variety.com/2020/artisans/awards/george-lucas-dolby-sound-star-wars-1203487459/",
    type: "artikel",
    epochen: ["New Hollywood"],
  },
  {
    id: "wiki-goodfellas",
    title: "Goodfellas",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/Goodfellas",
    type: "wikipedia",
    epochen: ["New Hollywood"],
  },
  // ── CGI-ÄRA ───────────────────────────────────────────────────────────────────
  {
    id: "histinfo-westworld",
    title: "Michael Crichton's Westworld, the First Major Film to Use Digital Image Processing",
    publisher: "historyofinformation.com",
    url: "https://www.historyofinformation.com/detail.php?id=1935",
    type: "artikel",
    epochen: ["CGI-Ära"],
  },
  {
    id: "guardian-tron",
    title: "'Frankly it blew my mind': how Tron changed cinema",
    publisher: "The Guardian",
    url: "https://www.theguardian.com/film/2022/jul/05/tron-steven-lisberger-interview",
    type: "artikel",
    epochen: ["CGI-Ära"],
  },
  {
    id: "roughcut-editdroid",
    title: "The Lost City of NLEs: How Lucasfilm Built and Buried EditDroid",
    publisher: "The Rough Cut",
    url: "https://roughcut.heyeddie.ai/p/the-lost-city-of-nles-how-lucasfilm",
    type: "artikel",
    epochen: ["CGI-Ära"],
  },
  {
    id: "wiki-avid",
    title: "Media Composer",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/Media_Composer",
    type: "wikipedia",
    epochen: ["CGI-Ära"],
  },
  {
    id: "ilm-jurassic",
    title: "Breathing Life into the Dinosaurs of Jurassic Park",
    publisher: "ILM (offiziell)",
    url: "https://www.ilm.com/creating-dinosaurs-jurassic-park/",
    type: "offiziell",
    epochen: ["CGI-Ära"],
  },
  {
    id: "wiki-toy-story",
    title: "Toy Story",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/Toy_Story",
    type: "wikipedia",
    epochen: ["CGI-Ära"],
  },
  {
    id: "wiki-dogme95",
    title: "Dogme 95",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/Dogme_95",
    type: "wikipedia",
    epochen: ["CGI-Ära"],
  },
  {
    id: "nofilmschool-matrix",
    title: "The Matrix's Most Iconic Move Was Almost Impossible",
    publisher: "No Film School",
    url: "https://nofilmschool.com/matrix-bullet-dodge-scene",
    type: "artikel",
    epochen: ["CGI-Ära"],
  },
  // ── DIGITAL ───────────────────────────────────────────────────────────────────
  {
    id: "redsharknews-lucas-digital",
    title: "How George Lucas Pioneered the Use of Digital Video with the Sony HDW-F900",
    publisher: "RedShark News",
    url: "https://www.redsharknews.com/technology-computing/item/2990-how-george-lucas-pioneered-the-use-of-digital-video-in-feature-films-with-the-sony-hdw-f900",
    type: "artikel",
    epochen: ["Digital"],
  },
  {
    id: "nyfa-red-cameras",
    title: "How RED Cameras Changed The Game",
    publisher: "New York Film Academy",
    url: "https://www.nyfa.edu/student-resources/how-red-cameras-changed-the-game/",
    type: "akademisch",
    epochen: ["Digital"],
  },
  {
    id: "wiki-canon-5d",
    title: "Canon EOS 5D Mark II",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/Canon_EOS_5D_Mark_II",
    type: "wikipedia",
    epochen: ["Digital"],
  },
  {
    id: "dpreview-5d-house",
    title: "'House' season finale filmed with Canon 5D Mark II",
    publisher: "DPReview",
    url: "https://www.dpreview.com/articles/7243371391/canon5dihouse",
    type: "artikel",
    epochen: ["Digital"],
  },
  {
    id: "definition-avatar",
    title: "The Cameras Of Avatar",
    publisher: "Definition Magazine",
    url: "https://definitionmagazine.com/features/the-cameras-of-avatar/",
    type: "artikel",
    epochen: ["Digital"],
  },
  {
    id: "newsshooter-alexa",
    title: "The ARRI ALEXA is 10 years old",
    publisher: "Newsshooter",
    url: "https://www.newsshooter.com/2020/05/27/the-arri-alexa-is-10-years-old/",
    type: "artikel",
    epochen: ["Digital"],
  },
  {
    id: "sfgate-35mm",
    title: "35mm era fades as theaters go digital",
    publisher: "San Francisco Chronicle",
    url: "https://www.sfgate.com/entertainment/article/35mm-era-fades-as-theaters-go-digital-3764461.php",
    type: "artikel",
    epochen: ["Digital"],
  },
  {
    id: "wiki-dolby-atmos",
    title: "Dolby Atmos",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/Dolby_Atmos",
    type: "wikipedia",
    epochen: ["Digital"],
  },
  {
    id: "sciencemuseum-oppenheimer-70mm",
    title: "The reel deal? Why you should watch Oppenheimer on 70mm film",
    publisher: "Science and Media Museum (Bradford)",
    url: "https://blog.scienceandmediamuseum.org.uk/oppenheimer-70mm/",
    type: "archiv",
    epochen: ["Digital"],
  },
  // ── KI-ÄRA ────────────────────────────────────────────────────────────────────
  {
    id: "netflix-lilyhammer",
    title: "Celebrating 10 Years of Netflix Series With 'Lilyhammer'",
    publisher: "Netflix (offiziell)",
    url: "https://about.netflix.com/news/celebrating-10-years-of-netflix-series-with-lilyhammer",
    type: "offiziell",
    epochen: ["KI-Ära"],
  },
  {
    id: "wiki-stagecraft",
    title: "StageCraft (ILM)",
    publisher: "Wikipedia (EN)",
    url: "https://en.wikipedia.org/wiki/StageCraft",
    type: "wikipedia",
    epochen: ["KI-Ära"],
  },
  {
    id: "techcrunch-mandalorian",
    title: "How The Mandalorian and ILM invisibly reinvented film and TV production",
    publisher: "TechCrunch",
    url: "https://techcrunch.com/2020/02/20/how-the-mandalorian-and-ilm-invisibly-reinvented-film-and-tv-production/",
    type: "artikel",
    epochen: ["KI-Ära"],
  },
  {
    id: "variety-runway-eeaao",
    title: "'Hollywood 2.0': How the Rise of AI Tools Like Runway Are Changing VFX",
    publisher: "Variety",
    url: "https://variety.com/2023/artisans/news/artificial-intelligence-runway-everything-everywhere-all-at-once-1235532322/",
    type: "artikel",
    epochen: ["KI-Ära"],
  },
  {
    id: "laedc-strikes",
    title: "Memo on the WGA and SAG-AFTRA Strikes",
    publisher: "Los Angeles Economic Development Corporation",
    url: "https://laedc.org/memo-on-the-wga-and-sag-aftra-strikes/",
    type: "akademisch",
    epochen: ["KI-Ära"],
  },
  {
    id: "openai-sora",
    title: "Sora: Creating video from text",
    publisher: "OpenAI (offiziell)",
    url: "https://openai.com/index/sora/",
    type: "offiziell",
    epochen: ["KI-Ära"],
  },
  {
    id: "openai-sora2",
    title: "Sora 2 is here",
    publisher: "OpenAI (offiziell)",
    url: "https://openai.com/index/sora-2/",
    type: "offiziell",
    epochen: ["KI-Ära"],
  },
  {
    id: "fastcompany-uncanny-valley",
    title: "China's new AI video tools close the uncanny valley for good",
    publisher: "Fast Company",
    url: "https://www.fastcompany.com/91489530/chinas-new-ai-video-tools-close-the-uncanny-valley-for-good",
    type: "artikel",
    epochen: ["KI-Ära"],
  },
];

export const typeLabels: Record<Source["type"], string> = {
  wikipedia: "Wikipedia",
  buch: "Buch",
  artikel: "Artikel / Fachpresse",
  archiv: "Archiv / Museum",
  offiziell: "Offizielle Quelle",
  akademisch: "Akademisch / Fachpublikation",
};
