// English translations for "Die Geschichte des Bewegtbildes"
// Design: "Dunkles Lichtspiel" – Dark Editorial Cinema

import type { TimelineEpoch, GlossaryEntry } from "./timelineData";

export const epochsEn: TimelineEpoch[] = [
  {
    id: "vorfilm",
    era: "Pre-Cinema",
    years: "until 1894",
    subtitle: "The Prehistory of the Moving Image",
    description: "Cinema was not invented. It was assembled – from centuries of experiments, toys and magic tricks.",
    entries: [
      {
        year: "Antiquity–1650",
        title: "Camera Obscura",
        body: "A hole in a wall, a dark room, an upside-down image of the outside world. Known since antiquity, described by Arab scholars in the 11th century. The principle of refraction is so simple that nature demonstrates it daily – in every leaf shadow during a solar eclipse.",
        type: "technik",
      },
      {
        year: "1659",
        title: "Magic Lantern",
        body: "Christiaan Huygens builds the first magic lantern – it projects painted glass slides onto a wall. Travelling preachers and showmen use the technology for Phantasmagoria spectacles: ghosts from nowhere, rear projections onto smoke. The first cinema was a horror-show tent at the fairground.",
        type: "technik",
        quote: "The first cinema was a horror-show tent at the fairground. Some things never change.",
      },
      {
        year: "1832",
        title: "Phénakistiscope",
        body: "Joseph Plateau publishes the Phénakistiscope – a rotating disc with slits that, when spun in front of a mirror, creates an illusion of movement. Simultaneously, Simon von Stampfer in Vienna develops the identical Stroboscope. The brain can be deceived. When images change fast enough, we see movement where there is none. The so-called Persistence of Vision is the foundation of every film ever made.",
        type: "technik",
      },
      {
        year: "1878",
        title: "Muybridge: The Horse in Motion",
        body: "Eadweard Muybridge stretches 24 cameras along a racetrack, connects them with trip wires and photographs a horse at full gallop. Result: yes, it does lift all four hooves simultaneously. And incidentally, Muybridge has invented high-speed photography. His Zoopraxiscope projects the images in sequence – the first time recorded movement can be seen again as movement.",
        type: "meilenstein",
      },
      {
        year: "1891",
        title: "Kinetoscope (Edison/Dickson)",
        body: "Thomas Edison has the Kinetoscope developed: a peep-show device into which you drop a coin and look through an eyepiece at a 35mm film strip. No projection, no shared experience, no screen. Edison thought this was the future. He was wrong.",
        type: "technik",
      },
    ],
  },
  {
    id: "geburt",
    era: "Birth of Cinema",
    years: "1895–1910",
    subtitle: "The Birth of Cinema",
    description: "28 December 1895. A train pulls into a station. Some spectators are said to have jumped up and run away.",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/101220242/eMM848s9vZH5Nks5dZfxni/lumiere_era-iZAxHf75ZboGFTbtC8hPJe.webp",
    entries: [
      {
        year: "28 Dec. 1895",
        title: "The Lumières' Cinématographe",
        body: "Auguste and Louis Lumière screen ten short films to paying audiences in the Salon Indien of the Grand Café in Paris. No script, no actors, no story. Just life, recorded and played back. The Cinématographe is camera, printer and projector in one – light enough to carry out into the world.",
        type: "meilenstein",
        quote: "The first cinema was simultaneously the first global medium.",
      },
      {
        year: "1895–1900",
        title: "The Lumières' Philosophy: Camera as Witness",
        body: "The Lumières believed cinema was an attraction without a future. Documentary testimony, not art. The camera stood still. The world walked past it. They sent cameramen to Russia, Japan, Mexico – everywhere. But the camera was not yet telling stories.",
        type: "filmsprache",
      },
      {
        year: "1896–1902",
        title: "Georges Méliès: Magician of Cinema",
        body: "The Parisian conjurer discovers the stop-trick by accident: the camera jams, he keeps filming, and on the developed film an omnibus transforms into a hearse. From this accident he builds a system. Double exposure. Dissolve. Time-lapse. Split screen. Miniature models. Méliès makes over 500 films.",
        type: "technik",
      },
      {
        year: "1902",
        title: "Voyage dans la Lune",
        body: "The first science-fiction film in history. 14 minutes, hand-coloured, with rockets, moon-men and the most famous image of early film history: the moon with a rocket in its eye. Méliès thinks in tableaux – frontal long shots, like on a theatre stage. The camera is the spectator's gaze, not a narrative instrument. That is his limitation.",
        type: "meilenstein",
      },
    ],
  },
  {
    id: "filmsprache",
    era: "Film Language",
    years: "1908–1929",
    subtitle: "The Invention of Film Language",
    description: "D.W. Griffith, Soviet montage theory and German Expressionism invent cinema as an independent narrative medium.",
    entries: [
      {
        year: "1908–1915",
        title: "D.W. Griffith: Close-Up and Cross-Cutting",
        body: "If one person had to be named who turned film into an independent narrative medium, it would be D.W. Griffith. That is uncomfortable, because his most famous film is racist propaganda. Both are true. He systematically develops: the close-up, cross-cutting, the flashback, the iris wipe.",
        type: "filmsprache",
        quote: "Griffith understood that the cut is a language of its own. That a close-up on a hand can say more than an entire monologue.",
      },
      {
        year: "1919–1927",
        title: "German Expressionism",
        body: "Caligari (1920), Nosferatu (1922), Metropolis (1927) – films in which the world is crooked because the souls are crooked. Oblique angles, extreme shadows, expressionist sets. Fritz Lang uses the Schüfftan process in Metropolis – a mirror technique that integrates actors into miniature sets. The first time film technology creates a reality that does not exist.",
        type: "filmsprache",
      },
      {
        year: "1921",
        title: "The Kuleshov Effect",
        body: "Lev Kuleshov demonstrates his famous experiment: he cuts the same neutral facial expression of an actor alternately with a bowl of soup, a coffin and a playing child. The audience sees hunger, grief and joy – even though the face is identical. Meaning is not created in the image, but between images.",
        type: "meilenstein",
        quote: "Meaning is not created in the image, but between images.",
      },
      {
        year: "1925",
        title: "Eisenstein: Intellectual Montage",
        body: "Sergei Eisenstein builds on Kuleshov and develops Intellectual Montage: images that together generate an idea that neither image contains alone. The Odessa Steps sequence in Battleship Potemkin is the most famous example – a sequence that creates emotional force through rhythm, contrast and repetition that far exceeds what is shown.",
        type: "filmsprache",
      },
      {
        year: "1929",
        title: "Dziga Vertov: Man with a Movie Camera",
        body: "Vertov's manifesto of the Kino-Eye: the camera sees better than the human eye. Slow motion, time-lapse, double exposure, split screen – all as tools of truth. A film without actors, without a script, without intertitles. Only camera and editing.",
        type: "filmsprache",
      },
    ],
  },
  {
    id: "tonfilm",
    era: "Sound Film",
    years: "1927–1939",
    subtitle: "Liberation and Captivity",
    description: "Sound film liberates cinema from the intertitle – and shackles the camera. Then comes colour.",
    entries: [
      {
        year: "6 Oct. 1927",
        title: "The Jazz Singer",
        body: "Al Jolson sings and says: »Wait a minute, wait a minute. You ain't heard nothin' yet.« The first synchronised dialogue in a feature film. The silent era ends – not immediately, but inexorably.",
        type: "meilenstein",
        quote: "»Wait a minute, wait a minute. You ain't heard nothin' yet.«",
      },
      {
        year: "1927–1930",
        title: "The Blimp: Camera in Captivity",
        body: "Early microphones are so sensitive that the noise of the camera drowns out everything. The solution: the camera goes into a soundproofed glass box, the blimp. Suddenly the camera stands still again, as in the very first years of cinema. Three years of progress in camera movement – gone.",
        type: "technik",
        quote: "Three years of progress in camera movement – gone.",
      },
      {
        year: "1931",
        title: "Fritz Lang: M – Sound Dramaturgy as Art",
        body: "Fritz Lang's M is the first masterpiece of the new language of sound. The murderer's whistled motif – a leitmotif that announces him before the image shows him – would simply have been impossible in a silent film. Thinking of image and sound as a single unit: that is the new task.",
        type: "filmsprache",
      },
      {
        year: "1932",
        title: "Technicolor Three-Strip",
        body: "Three separate negatives for red, green and blue, combined into a colour image. Walt Disney uses it in 1932 for Flowers and Trees – the first animated film in full colour. The first feature film: Becky Sharp (1935).",
        type: "technik",
      },
      {
        year: "1939",
        title: "The Wizard of Oz: Colour as Dramaturgy",
        body: "Kansas is black and white. Oz is Technicolor. That is not a technical decision, it is dramaturgy. Colour as metaphor. From this moment on it is clear: technology and film language are not separate things. They are the same thing.",
        type: "meilenstein",
        quote: "Colour as metaphor. From this moment on it is clear: technology and film language are not separate things. They are the same thing.",
      },
    ],
  },
  {
    id: "goldenhollywood",
    era: "Golden Hollywood",
    years: "1941–1965",
    subtitle: "Depth, Noir and the Widescreen",
    description: "Orson Welles invents deep focus. Film Noir makes light the narrator. Hollywood answers television with the widescreen.",
    entries: [
      {
        year: "1941",
        title: "Citizen Kane: Deep Focus and Wide Angle",
        body: "Orson Welles was 25 years old, had never directed a film, and was given complete artistic control. With cinematographer Gregg Toland he develops deep focus as a stylistic device: everything in the frame is sharp, from front to back. Extreme low angles, ceiling shots, wide-angle lenses. Citizen Kane is a textbook of cinematography still used in film schools today.",
        type: "meilenstein",
        quote: "Deep focus means the viewer can decide for themselves where to look.",
      },
      {
        year: "1940s–50s",
        title: "Film Noir: Light as Narrator",
        body: "Hard light, deep shadows, oblique angles, moral ambiguity. Technically a question of lighting: little light, precisely placed, creates more tension than a fully lit set. German Expressionism, Americanised.",
        type: "filmsprache",
      },
      {
        year: "1953",
        title: "CinemaScope: Answer to Television",
        body: "Television has 4:3. Hollywood answers with CinemaScope, VistaVision, Todd-AO. Wider. Bigger. More. The 2.35:1 aspect ratio is still the standard format for epic films today – and it exists because television had 4:3.",
        type: "technik",
      },
      {
        year: "1958",
        title: "Dolly Zoom: Technology as Psychology",
        body: "Cinematographer Irmin Roberts invents the dolly zoom effect for Hitchcock's Vertigo: the camera tracks back while the lens simultaneously zooms in. The subject remains the same size, but the background changes dramatically. A physically impossible feeling – dizziness, disorientation, fear – translated directly into the image.",
        type: "meilenstein",
      },
    ],
  },
  {
    id: "nouvellvague",
    era: "Nouvelle Vague",
    years: "1958–1968",
    subtitle: "The Liberated Camera",
    description: "Lightweight cameras, natural light, streets instead of studios. The Nouvelle Vague turns rule-breaking into a new language.",
    entries: [
      {
        year: "1958",
        title: "Arriflex 35: The Camera Gets Light",
        body: "A camera light enough to carry on the shoulder. At the same time, lighter sound recording devices emerge. The result is a movement that was not planned but seemed inevitable: the Nouvelle Vague.",
        type: "technik",
      },
      {
        year: "1959–1962",
        title: "Godard, Truffaut, Varda: Jump Cut and Auteur",
        body: "Godard's Breathless (1960) is the manifesto. The jump cut – an edit that violates all rules of continuity – was not a mistake. It was a statement: cinema does not have to pretend to be invisible. The Nouvelle Vague establishes the auteur theory: the director is the author of the film.",
        type: "filmsprache",
        quote: "Cinema does not have to pretend to be invisible.",
      },
      {
        year: "1944–1960",
        title: "Italian Neorealism",
        body: "Vittorio De Sica, Roberto Rossellini: exterior shots, non-professional actors, natural light. The camera goes out into the street. Martin Scorsese called Neorealism 'the rehabilitation of an entire culture and people through cinema'.",
        type: "filmsprache",
      },
    ],
  },
  {
    id: "newhollywood",
    era: "New Hollywood",
    years: "1967–1980",
    subtitle: "The Film School Generation",
    description: "Scorsese, Coppola, Spielberg, Lucas. They had studied Eisenstein and Godard and brought European art cinema to America.",
    entries: [
      {
        year: "1975",
        title: "Steadicam: Freedom and Stability",
        body: "Garrett Brown invents the Steadicam. A counterbalance system decouples the camera from the cameraman's body movements. The result is a movement as smooth as a dolly, but able to go anywhere. First use: Bound for Glory (1976). Made famous by Rocky (1976) and The Shining (1980).",
        type: "technik",
        quote: "The Steadicam combines the stability of the dolly with the freedom of the handheld camera.",
      },
      {
        year: "1975–1977",
        title: "Jaws and Star Wars: The Blockbuster",
        body: "Spielberg and Lucas end New Hollywood – not intentionally, but effectively. Jaws (1975) and Star Wars (1977) invent the blockbuster. Lucas founds ILM and revolutionises cinema sound: Dolby Stereo turns cinema into an acoustic experience that could not be reproduced at home.",
        type: "meilenstein",
      },
      {
        year: "1980",
        title: "The Shining: Steadicam as Style",
        body: "Kubrick uses the Steadicam for the maze chase sequence – an effect that would have been impossible with any other technique. Scorsese's Copacabana shot in Goodfellas (1990) becomes the most famous Steadicam masterpiece: almost three minutes without a single cut.",
        type: "filmsprache",
      },
    ],
  },
  {
    id: "cgi",
    era: "CGI Era",
    years: "1973–1999",
    subtitle: "The Computer Enters Cinema",
    description: "From the first pixelated robot eyes to photorealistic dinosaurs and a camera that can be anywhere.",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/101220242/eMM848s9vZH5Nks5dZfxni/digital_era-U5XNHp92gayFefhXFnQP86.webp",
    entries: [
      {
        year: "1973",
        title: "Westworld: First Digital Image Processing",
        body: "Michael Crichton's Westworld uses digital image processing to simulate the pixelated vision of a robot. The first time a computer produces images for a cinema film. Nobody suspected then what would come of it.",
        type: "technik",
      },
      {
        year: "1982",
        title: "Tron: 15 Minutes of CGI",
        body: "Tron shows 15 minutes of fully computer-generated images. The technology is breathtaking for its time. Audiences are moderately impressed. But the door is open.",
        type: "technik",
      },
      {
        year: "1984",
        title: "EditDroid: Foundation of Digital Editing",
        body: "Lucasfilm presents the EditDroid at the NAB trade show – a non-linear editing system based on LaserDisc. For the first time, clips can be called up in any order, a timeline viewed on screen and cuts made without physically cutting film. The core concepts – clip bins, timeline, digital preview – are still found in every editing application today.",
        type: "technik",
      },
      {
        year: "1989",
        title: "Avid Media Composer: Digital Editing",
        body: "The first fully digital NLE system running on a Macintosh. Expensive, image quality modest, storage capacity limited. But it works. And it changes the industry completely within a few years.",
        type: "meilenstein",
      },
      {
        year: "1993",
        title: "Jurassic Park: CGI Can Replace Anything",
        body: "Steven Spielberg asks ILM whether photorealistic dinosaurs are possible. The answer: maybe. The result is a turning point in film history. The CGI dinosaurs do not look like computer images. They look like animals. The audience believes in them.",
        type: "meilenstein",
        quote: "From that moment on it was clear: CGI can replace anything.",
      },
      {
        year: "1995",
        title: "Toy Story: First Fully CGI Film",
        body: "Pixar proves that CGI does not have to imitate reality to work. A stylised, non-realistic look can move audiences just as deeply as any photograph.",
        type: "meilenstein",
      },
      {
        year: "1995",
        title: "Dogme 95: Reaction Against CGI",
        body: "Lars von Trier and Thomas Vinterberg publish their manifesto: handheld camera only, natural light, no special effects, no director credit. Dogme 95 is a reaction against CGI excess. The Vows of Chastity as liberation through constraint.",
        type: "gegenreaktion",
        quote: "Liberation through constraint.",
      },
      {
        year: "1999",
        title: "The Matrix: Bullet Time",
        body: "An array of roughly 99 to 120 still cameras arranged in an arc around the actor. The individual frames are assembled into a flowing movement that simulates a camera move that does not exist. A single shot that changes cinema – and that is copied in every commercial over the following years until it becomes parody.",
        type: "meilenstein",
      },
    ],
  },
  {
    id: "digital",
    era: "Digital",
    years: "2002–2015",
    subtitle: "The End of Film Stock",
    description: "RED, DSLR, ARRI Alexa. Film stock disappears from cinemas. And one fighter holds out.",
    entries: [
      {
        year: "2002",
        title: "Star Wars Episode II: First Major Digital Film",
        body: "George Lucas shoots Star Wars Episode II entirely digitally on the Sony HDW-F900. The first major feature film without film stock.",
        type: "technik",
      },
      {
        year: "2007",
        title: "RED ONE: 4K for Everyone",
        body: "Jim Jannard founds RED Digital Cinema. 4K resolution at the price of a film camera. The democratisation of professional filmmaking begins.",
        type: "technik",
      },
      {
        year: "2008",
        title: "Canon 5D Mark II: The DSLR Revolution",
        body: "A DSLR camera for photographers that incidentally records Full HD video. Shallow depth of field, cinematic bokeh – for €2,500. An episode of the hospital series House (M.D.) is shot on a 5D Mark II – the first time a DSLR is used for a US television production. Anyone can now produce images that look like cinema.",
        type: "meilenstein",
        quote: "Anyone can now produce images that look like cinema.",
      },
      {
        year: "2009",
        title: "Avatar: Virtual Camera",
        body: "James Cameron develops a virtual camera with which he can navigate through the CGI world as if through a real set. 3D renaissance. Motion capture at a new level.",
        type: "technik",
      },
      {
        year: "2010",
        title: "ARRI Alexa: Digital Film Look",
        body: "The Alexa becomes the dominant camera in Hollywood – not because of resolution, but because of the image. Warm skin tones, natural grain, a dynamic range that recalls film stock. At a time when everything goes digital, the Alexa offers the best of both worlds.",
        type: "technik",
      },
      {
        year: "2012",
        title: "End of 35mm Film Stock in Cinemas",
        body: "By this year most cinemas worldwide have switched to digital projection. The 35mm film strip, which had been the medium of cinema since the 1890s, disappears from projection booths. No more heavy film reels. But also: no more patina, no more imperfection.",
        type: "meilenstein",
      },
      {
        year: "2012",
        title: "Dolby Atmos: Object-Based Surround Sound",
        body: "Instead of fixed channels, Atmos works with sound objects: each sound has a position in three-dimensional space. A helicopter flies over the heads of the audience. That changes how directors think about sound.",
        type: "technik",
      },
      {
        year: "2014–today",
        title: "Nolan Fights for 35mm",
        body: "Christopher Nolan shoots Interstellar (2014), Dunkirk (2017), Oppenheimer (2023) on 35mm or 70mm. This is not sentimentality. It is an aesthetic decision that produces a specific image quality. The most prominent advocate for analogue film stock in a fully digital world.",
        type: "gegenreaktion",
      },
    ],
  },
  {
    id: "ki",
    era: "AI Era",
    years: "2015–2026",
    subtitle: "Fundamental Questions",
    description: "Streaming, LED volumes, generative AI. What does filmmaking mean when a sentence of text generates a video?",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/101220242/eMM848s9vZH5Nks5dZfxni/digital_era-U5XNHp92gayFefhXFnQP86.webp",
    entries: [
      {
        year: "2013–today",
        title: "Netflix as Producer",
        body: "House of Cards (2013) is the first studio-produced Netflix series – the very first Netflix Original was Lilyhammer (2012). Netflix changes financing and distribution. Binge-watching changes dramaturgy: serial storytelling, cliffhangers as standard, episode structure as art form.",
        type: "meilenstein",
      },
      {
        year: "2019",
        title: "The Mandalorian: LED Volume",
        body: "Almost none of the exterior scenes are shot outside. Instead, the crew stands inside a huge circular LED wall – the ILM StageCraft system. Real-time rendering with Unreal Engine. The light of the environment actually falls on the actors. The return to a controlled environment – but with real-time CGI instead of painted backdrops.",
        type: "meilenstein",
        quote: "This is the return to something Méliès already knew: control over the environment is control over the image.",
      },
      {
        year: "2022–2023",
        title: "Runway and AI in Post-Production",
        body: "Everything Everywhere All at Once uses the AI tool Runway in post-production – not for entire scenes, but as an auxiliary tool for rotoscoping and compositing. A small team, a small budget, maximum impact. That is the point.",
        type: "technik",
      },
      {
        year: "2023",
        title: "WGA/SAG-AFTRA Strike: AI as Threat",
        body: "The first major strike in Hollywood in decades. Central questions: who owns a screenplay that an AI system co-wrote? May a studio use an actor's digital likeness in a film for which they were not paid? These questions are still not fully answered.",
        type: "gegenreaktion",
      },
      {
        year: "Feb. 2024",
        title: "OpenAI Sora: Text-to-Video",
        body: "A model that generates videos from text descriptions. The first examples are astonishing. Not perfect – hands have too many fingers, physics sometimes behaves strangely – but astonishing. A beach, a woman, golden light, a camera move that looks like a professional shoot. From a single sentence of text.",
        type: "meilenstein",
        quote: "When every camera move is possible, when every environment can be generated – what is the statement of a single shot?",
      },
      {
        year: "2025–2026",
        title: "Kling, Seedance, Sora 2: The Uncanny Valley Closes",
        body: "Chinese AI video tools produce qualities that some describe as the closing of the uncanny valley. Videos barely distinguishable from real film footage. Sora 2 appears in September 2025. The boundary between filmed and generated video grows blurrier.",
        type: "meilenstein",
      },
    ],
  },
];

export const glossaryEn: GlossaryEntry[] = [
  // Technology
  { term: "35mm Film Stock", category: "technik", year: "1892", definition: "The standard format for cinema film established by Edison and Dickson: 35-millimetre-wide celluloid material with perforations along the edges. Was the dominant recording and projection medium from the 1890s to the 2010s." },
  { term: "Arriflex 35", category: "technik", year: "1937", definition: "Handheld 35mm film camera by the German company ARRI. Its low weight enabled truly mobile camerawork for the first time and became the technical foundation of the Nouvelle Vague." },
  { term: "ARRI Alexa", category: "technik", year: "2010", definition: "Digital cinema camera by ARRI that aesthetically imitates analogue film stock through its image characteristics – warm skin tones, natural grain, high dynamic range. The most widely used camera in Hollywood productions since its introduction." },
  { term: "Avid Media Composer", category: "technik", year: "1989", definition: "The first professionally used non-linear editing system (NLE) on a computer. Revolutionised post-production: instead of physically cutting film strips, clips were arranged digitally on a timeline." },
  { term: "Blimp", category: "technik", year: "1927", definition: "Soundproofed housing for film cameras that dampens the operating noise of the camera motor. Became necessary with the introduction of sound film, as sensitive microphones picked up camera noise – and shackled the camera to the tripod for several years." },
  { term: "Bullet Time", category: "technik", year: "1999", definition: "Effect technique developed for The Matrix: hundreds of still cameras are arranged in an arc around the subject and fire in rapid succession. The individual frames produce a camera move that would be physically impossible – the world seems to freeze while the camera circles it." },
  { term: "Camera Obscura", category: "technik", definition: "Latin for 'dark chamber'. Optical principle: light passes through a small hole into a dark room and projects an inverted image of the outside world onto the opposite wall. Known since antiquity, precursor of photography and cinema." },
  { term: "CGI", category: "technik", year: "1973", definition: "Computer-Generated Imagery. Computer-generated images and animations in film. First use in 1973 in Westworld, breakthrough in 1993 with Jurassic Park, today ubiquitous from blockbusters to television productions." },
  { term: "Cinématographe", category: "technik", year: "1895", definition: "Device developed by the Lumière brothers that was simultaneously camera, film printer and projector. Light and portable, it enabled public film screenings before paying audiences for the first time. First screened on 28 December 1895 in Paris." },
  { term: "CinemaScope", category: "format", year: "1953", definition: "Anamorphic widescreen format with an aspect ratio of 2.35:1, developed as a response to the rise of television (4:3). A special lens horizontally squeezes the image during shooting and stretches it again during projection." },
  { term: "Dolby Atmos", category: "technik", year: "2012", definition: "Object-based surround sound system by Dolby. Instead of fixed audio tracks, sound objects are defined with three-dimensional positions in space. Enables precise sound movement above and around the audience." },
  { term: "Dolby Stereo", category: "technik", year: "1975", definition: "Multi-channel sound system that became popular with Star Wars (1977). For the first time, cinema sound could be experienced spatially – sounds came from different directions. Made cinema as an acoustic experience impossible to reproduce at home." },
  { term: "Dolly", category: "technik", definition: "Wheeled or tracked carriage on which the camera is mounted. Enables smooth, controlled camera moves. A fundamental tool since the early 1910s." },
  { term: "EditDroid", category: "technik", year: "1984", definition: "Non-linear editing system developed by Lucasfilm, based on LaserDisc. Precursor of modern NLE software: for the first time clips could be called up in any order and cuts made without physically cutting film." },
  { term: "Kinetoscope", category: "technik", year: "1891", definition: "Peep-show device developed by Thomas Edison and William Dickson: a single viewer looks through an eyepiece at a running 35mm film strip. No projection, no shared experience. Edison believed this was the future of film – he was wrong." },
  { term: "Magic Lantern", category: "technik", year: "1659", definition: "Precursor of the slide projector developed by Christiaan Huygens: a light source projects painted glass slides onto a wall or curtain. Used by showmen for Phantasmagoria spectacles – the first 'cinema' was a fairground horror show." },
  { term: "LED Volume", category: "technik", year: "2019", definition: "Also 'Virtual Production Stage': a huge curved LED wall displays photorealistic rendered backgrounds in real time. Actors perform in front of the wall; the camera captures foreground and background together. Developed by ILM for The Mandalorian." },
  { term: "Motion Capture", category: "technik", year: "2000s", definition: "Process for recording movement: actors wear suits with tracking markers whose positions are captured by cameras and transferred to digital characters. Enables photorealistic CGI figures with human movement qualities." },
  { term: "NLE", category: "technik", year: "1989", definition: "Non-Linear Editing. Digital editing system in which clips can be arranged in any order on a computer-based timeline – as opposed to linear editing, in which film strips were physically cut and spliced." },
  { term: "Phénakistiscope", category: "technik", year: "1832", definition: "Optical toy invented by Joseph Plateau: a rotating disc with slits and drawn movement phases creates the illusion of movement when spun in front of a mirror. Uses the principle of Persistence of Vision." },
  { term: "RED ONE", category: "technik", year: "2007", definition: "First 4K digital cinema camera at a price affordable for independent filmmakers. Founded by Jim Jannard, RED considerably democratised professional filmmaking." },
  { term: "Schüfftan Process", category: "technik", year: "1923", definition: "Mirror technique developed by Eugen Schüfftan: a half-silvered mirror combines actors with miniature models or painted backgrounds in a single camera image. First used in Metropolis (1927) – precursor of modern compositing techniques." },
  { term: "Steadicam", category: "technik", year: "1975", definition: "Camera stabilisation system invented by Garrett Brown: a counterbalance mechanism decouples the camera from the cameraman's body movements. The result is a smooth, stable movement that is neither dolly nor handheld." },
  { term: "Technicolor", category: "technik", year: "1916", definition: "Colour film process that in its three-strip version (1932) exposed three separate negatives for red, green and blue and combined them into a colour image. Known through The Wizard of Oz (1939) and many classics of Golden Hollywood." },
  { term: "Zoopraxiscope", category: "technik", year: "1879", definition: "Precursor of the film projector developed by Eadweard Muybridge: a rotating glass disc with photographs in movement sequence is spun in front of a light source and projects the images in rapid succession – for the first time, recorded movement could be seen again as movement." },
  // Film Language
  { term: "Auteur Theory", category: "filmsprache", year: "1954", definition: "Theory formulated by Cahiers du Cinéma critics (later Nouvelle Vague directors): the director is the true author of a film – just as a writer is the author of a novel. The director shapes all aspects of the film through their personal style." },
  { term: "Close-Up", category: "filmsprache", definition: "The camera shows a detail at close range, usually a face or an object. Systematically used as a narrative device by D.W. Griffith: a close-up on a hand can say more than an entire monologue." },
  { term: "Dolly Zoom", category: "filmsprache", year: "1958", definition: "Also 'Vertigo effect' or 'Hitchcock zoom': the camera tracks back (or forward) while the lens simultaneously zooms in (or out). The subject remains the same size, but the background changes dramatically – a physically impossible feeling of dizziness and disorientation." },
  { term: "Flashback", category: "filmsprache", definition: "A scene that takes place before the current moment of the narrative. Developed as a narrative device by D.W. Griffith, today a standard element of film dramaturgy." },
  { term: "Handheld Camera", category: "filmsprache", year: "1958", definition: "The camera is carried by the cameraman rather than mounted on a tripod or dolly. Creates an unsteady, documentary image aesthetic. Established as a stylistic device by the Nouvelle Vague, elevated to a principle by Dogme 95." },
  { term: "Intellectual Montage", category: "filmsprache", year: "1925", definition: "Editing principle developed by Sergei Eisenstein: two images together generate an idea that neither image contains alone. Going beyond the Kuleshov effect, intellectual montage aims at abstract thoughts and political statements." },
  { term: "Jump Cut", category: "filmsprache", year: "1960", definition: "An edit that violates continuity rules: two shots of the same scene are cut together even though a visible discontinuity results. Used by Godard in Breathless (1960) as a conscious stylistic statement." },
  { term: "Kino-Eye", category: "filmsprache", year: "1924", definition: "Dziga Vertov's theory: the camera sees better than the human eye. Slow motion, time-lapse, unusual angles – all are tools to show a truth that the naked eye cannot see. Foundation of documentary cinema." },
  { term: "Kuleshov Effect", category: "filmsprache", year: "1921", definition: "Montage principle demonstrated by Lev Kuleshov: the same neutral facial expression appears different depending on which image is cut before or after it. Meaning is not created in the image, but between images." },
  { term: "Leitmotif", category: "filmsprache", definition: "Recurring musical or visual motif associated with a character, place or idea. Used as a dramatic device in sound film by Fritz Lang (M, 1931): the murderer's whistled motif announces him before the image shows him." },
  { term: "Cross-Cutting", category: "filmsprache", year: "1908", definition: "Editing technique developed by D.W. Griffith: two simultaneously occurring storylines are shown alternately. Creates tension through the implicit question: who arrives first?" },
  { term: "Persistence of Vision", category: "filmsprache", definition: "Physiological phenomenon: the human brain retains an image briefly after it disappears. When images change fast enough (from about 16 frames per second), the brain perceives them as continuous movement. The basic principle of cinema." },
  { term: "Phantasmagoria", category: "filmsprache", year: "1790s", definition: "Spectacle format of the 18th and early 19th centuries: using the magic lantern, ghosts and horror images were projected onto smoke or thin screens. The first 'cinema' was a fairground horror show." },
  { term: "Tableau", category: "filmsprache", definition: "Frontal long shot, as on a theatre stage: the camera stands still, actors perform in front of it as before an audience. Stylistic principle of early film history (Méliès, early Lumières), overcome by Griffith in favour of editing." },
  { term: "Deep Focus", category: "filmsprache", year: "1941", definition: "Optical phenomenon: the area in which the image is sharp extends from near to far. Used as a stylistic device by Orson Welles and cinematographer Gregg Toland in Citizen Kane (1941): everything in the frame is simultaneously sharp – the viewer decides for themselves where to look." },
  { term: "Sound Dramaturgy", category: "filmsprache", year: "1931", definition: "The conscious dramatic use of sound, music and silence as a narrative device. Fritz Lang's M (1931) is considered the first masterpiece of sound dramaturgy: the murderer's whistled motif is not just sound, but narrative." },
  { term: "Uncanny Valley", category: "filmsprache", definition: "Psychological phenomenon: when a digital figure or AI-generated image looks almost, but not quite, human, it creates unease. Named after Japanese roboticist Masahiro Mori. In the context of AI video: the uncanny valley closes when generated images can no longer be distinguished from real ones." },
  // Movements
  { term: "Dogme 95", category: "bewegung", year: "1995", definition: "Film manifesto written by Lars von Trier and Thomas Vinterberg: handheld camera only, natural light, no special effects, no genre films, no director credit. The 'Vows of Chastity' as a reaction against CGI excess of the 1990s – liberation through constraint." },
  { term: "Expressionism", category: "bewegung", year: "1919", definition: "Film aesthetic of German silent cinema: oblique angles, extreme shadows, expressionist sets reflect the inner turmoil of the characters. Caligari (1920), Nosferatu (1922), Metropolis (1927). Influenced American Film Noir of the 1940s." },
  { term: "Film Noir", category: "bewegung", year: "1940s", definition: "American film aesthetic of the 1940s and 50s: hard light, deep shadows, oblique angles, moral ambiguity. Technically a question of lighting – little light, precisely placed. German Expressionism, Americanised." },
  { term: "ILM", category: "technik", year: "1975", definition: "Industrial Light & Magic. Special effects studio founded by George Lucas for Star Wars (1977). Developed pioneering techniques for optical and digital special effects, including the CGI dinosaurs in Jurassic Park (1993) and the LED volume system StageCraft (2019)." },
  { term: "Neorealism", category: "bewegung", year: "1944", definition: "Italian film movement after the Second World War: exterior shots, non-professional actors, natural light, social themes. Vittorio De Sica, Roberto Rossellini. The camera goes out into the street. Precursor of the Nouvelle Vague and documentary film." },
  { term: "New Hollywood", category: "bewegung", year: "1967", definition: "American film generation of the late 1960s and 1970s: Scorsese, Coppola, Spielberg, Lucas. Brought European art cinema to America – personal stories, complex characters, unconventional structures. Ended with the blockbuster era from 1975." },
  { term: "Nouvelle Vague", category: "bewegung", year: "1958", definition: "French film movement of the late 1950s and 1960s: Godard, Truffaut, Varda, Chabrol. Lightweight cameras, natural light, street shoots instead of studio productions. Established the auteur theory and the jump cut as stylistic devices." },
  // Formats
  { term: "4:3", category: "format", definition: "Aspect ratio of early cinema and analogue television. Approximately square. Overcome by cinema with the widescreen format when television became a competitor in the 1950s." },
  { term: "2.35:1", category: "format", definition: "Anamorphic widescreen format introduced with CinemaScope (1953). Today the standard format for epic feature films. Exists because television had 4:3." },
  { term: "4K", category: "format", year: "2007", definition: "Digital resolution of approximately 4096 × 2160 pixels (cinema) or 3840 × 2160 pixels (UHD). First made affordable for independent filmmakers with the RED ONE (2007). Today the standard in film production." },
  { term: "Virtual Production", category: "technik", year: "2019", definition: "Production method in which digital environments are rendered in real time on LED walls or in computers and captured directly by the camera. Enables complete control over light and environment without exterior shooting. Developed by ILM for The Mandalorian." },
  { term: "VFX", category: "technik", definition: "Visual Effects. Visual special effects added or altered digitally in post-production. Distinct from practical effects (on set): VFX are created on a computer." },
  { term: "Bokeh", category: "filmsprache", definition: "Japanese term for the aesthetic quality of the out-of-focus area of a photograph or film image. Shallow bokeh (shallow depth of field) creates a cinematic look – the background blurs, the subject stands out. Made accessible to everyone with the DSLR revolution (2008)." },
  { term: "Dynamic Range", category: "technik", definition: "The range between the brightest and darkest areas a recording medium can simultaneously represent. Film stock traditionally has a higher dynamic range than digital sensors – one reason why analogue recordings often appear 'softer'." },
  { term: "Double Exposure", category: "technik", year: "1896", definition: "Technique in which the same piece of film is exposed twice, so that two images appear superimposed. Discovered and systematically used as a trick technique by Méliès. Today realised digitally as 'compositing'." },
  { term: "Compositing", category: "technik", definition: "Digital combination of multiple image layers into a final image. Modern equivalent of the Schüfftan process and double exposure. The foundation of all modern VFX productions." },
  { term: "Aspect Ratio", category: "format", definition: "The ratio of width to height of a film image. Fundamentally determines the visual impact: 4:3 feels compact and intimate, 2.35:1 epic and expansive. The history of aspect ratio is a history of competition between cinema and television." },
];

export const milestoneTableEn = [
  { year: "1832", technik: "Phénakistiscope", filmsprache: "Basic principle of motion illusion" },
  { year: "1878", technik: "Muybridge: Horse in Motion", filmsprache: "First motion sequence from photographs" },
  { year: "1895", technik: "Cinématographe (Lumière)", filmsprache: "First public cinema screening" },
  { year: "1902", technik: "Stop trick (Méliès)", filmsprache: "First trick technique, first sci-fi" },
  { year: "1908–15", technik: "Lighter cameras", filmsprache: "Close-up, cross-cutting (Griffith)" },
  { year: "1921", technik: "Editing experiment", filmsprache: "Kuleshov Effect: meaning between images" },
  { year: "1927", technik: "Sound film / Blimp", filmsprache: "Camera freezes, then liberation" },
  { year: "1932–39", technik: "Technicolor 3-Strip", filmsprache: "Colour as dramatic device" },
  { year: "1941", technik: "Deep focus / Wide angle", filmsprache: "Citizen Kane – camera as narrator" },
  { year: "1953", technik: "CinemaScope", filmsprache: "Widescreen as answer to TV" },
  { year: "1958", technik: "Arriflex 35 (lightweight)", filmsprache: "Nouvelle Vague, jump cut, handheld" },
  { year: "1975", technik: "Steadicam", filmsprache: "Fluid movement without dolly" },
  { year: "1977", technik: "ILM / Dolby Stereo", filmsprache: "Special effects and sound as experience" },
  { year: "1989", technik: "Avid Media Composer", filmsprache: "Digital editing revolutionises post-production" },
  { year: "1993", technik: "CGI (Jurassic Park)", filmsprache: "Photorealistic CGI – turning point" },
  { year: "1995", technik: "Dogme 95", filmsprache: "Reaction: liberation through constraint" },
  { year: "1999", technik: "Bullet Time (Matrix)", filmsprache: "Physically impossible camera moves" },
  { year: "2008", technik: "Canon 5D Mark II", filmsprache: "DSLR revolution, indie film for all" },
  { year: "2012", technik: "Dolby Atmos / Digital projection", filmsprache: "End of 35mm film stock in cinemas" },
  { year: "2019", technik: "LED Volume (ILM StageCraft)", filmsprache: "Virtual production as new standard" },
  { year: "2024", technik: "OpenAI Sora", filmsprache: "Text-to-video – fundamental questions" },
];

// UI string translations
export const uiEn = {
  siteTitle: "The History of the Moving Image",
  heroSubtitle: "From the Camera Obscura to AI. How technology and film language challenged, liberated and sometimes shackled each other.",
  heroLabel: "An Interactive Timeline",
  heroLink: "Explore the timeline",
  introHeading: "A History of Mutual Dependency",
  introText: "Every new technology in film history has done the same thing: first it constrained, then it liberated. The sound film froze the camera. The Steadicam freed it again. CGI made everything possible. Dogme 95 said: enough. This timeline traces that pattern – from the Camera Obscura to Sora 2.",
  overviewTitle: "Overview",
  overviewSubtitle: "Technology & Film Language",
  overviewDesc: "Each row shows how a technical innovation and a development in film language belong together – or how they created each other.",
  overviewColYear: "Year",
  overviewColTech: "Technology",
  overviewColFilm: "Film Language / Consequence",
  glossaryTitle: "Glossary",
  glossaryLabel: "Terms & Definitions",
  glossaryDesc: "All technical terms, film language concepts, movements and formats from the timeline – explained in context.",
  glossarySearch: "Search terms…",
  glossaryCatAll: "All",
  glossaryCatTechnik: "Technology",
  glossaryCatFilmsprache: "Film Language",
  glossaryCatBewegung: "Movements",
  glossaryCatFormat: "Formats",
  sourcesTitle: "Sources",
  sourcesLabel: "Fact-Check & References",
  sourcesDesc: "sources were verified as part of a systematic fact-check (March 2026). Errors and inaccuracies were corrected. Filterable by epoch and source type.",
  sourcesStand: "As of March 2026. All links verified at time of publication.",
  sourcesFilterEpoch: "Epoch",
  sourcesFilterType: "Type",
  closingQuote: "\"The history of cinema is the history of a technology that kept asking: what can I do now? And a language that kept answering: this.\"",
  legendTechnik: "Technology",
  legendFilmsprache: "Film Language",
  legendGegenreaktion: "Counter-reaction",
  legendMeilenstein: "Milestone",
  navOverview: "Overview",
  navGlossar: "Glossary",
  navQuellen: "Sources",
};
